# Generated by Django 4.1.3 on 2022-11-17 18:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hizmetler', verbose_name='Resim Ekle')),
                ('icon', models.ImageField(upload_to='hizmetler/icon', verbose_name='İcon Ekle')),
                ('title', models.CharField(max_length=150, verbose_name='Hizmet Başlığı')),
                ('description', models.TextField(verbose_name='Ön Açıklama')),
                ('description1', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ana Açıklama')),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
