# Generated by Django 4.1.3 on 2022-11-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_servicesmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='image1',
            field=models.ImageField(default='img/default.png', upload_to='hizmetler', verbose_name='Resim Ekle'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='image10',
            field=models.ImageField(default='img/default.png', upload_to='hizmetler', verbose_name='Resim Ekle'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='image2',
            field=models.ImageField(default='img/default.png', upload_to='hizmetler', verbose_name='Resim Ekle'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='image3',
            field=models.ImageField(default='img/default.png', upload_to='hizmetler', verbose_name='Resim Ekle'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='image4',
            field=models.ImageField(default='img/default.png', upload_to='hizmetler', verbose_name='Resim Ekle'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='image5',
            field=models.ImageField(default='img/default.png', upload_to='hizmetler', verbose_name='Resim Ekle'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='image6',
            field=models.ImageField(default='img/default.png', upload_to='hizmetler', verbose_name='Resim Ekle'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='image7',
            field=models.ImageField(default='img/default.png', upload_to='hizmetler', verbose_name='Resim Ekle'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='image8',
            field=models.ImageField(default='img/default.png', upload_to='hizmetler', verbose_name='Resim Ekle'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='image9',
            field=models.ImageField(default='img/default.png', upload_to='hizmetler', verbose_name='Resim Ekle'),
        ),
    ]
