# Generated by Django 4.1.3 on 2022-11-17 23:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_servicesmodel_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project', verbose_name='Resim Ekle')),
                ('title', models.CharField(max_length=150, verbose_name='Hizmet Başlığı')),
                ('description', models.TextField(verbose_name='Ön Açıklama')),
                ('description1', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ana Açıklama')),
                ('image1', models.ImageField(upload_to='project', verbose_name='Resim Ekle')),
                ('image2', models.ImageField(upload_to='project', verbose_name='Resim Ekle')),
                ('image3', models.ImageField(upload_to='project', verbose_name='Resim Ekle')),
                ('image4', models.ImageField(upload_to='project', verbose_name='Resim Ekle')),
                ('image5', models.ImageField(upload_to='project', verbose_name='Resim Ekle')),
                ('image6', models.ImageField(upload_to='project', verbose_name='Resim Ekle')),
                ('image7', models.ImageField(upload_to='project', verbose_name='Resim Ekle')),
                ('image8', models.ImageField(upload_to='project', verbose_name='Resim Ekle')),
                ('image9', models.ImageField(upload_to='project', verbose_name='Resim Ekle')),
                ('is_home', models.BooleanField(verbose_name='Ana Sayfada Gösterilsin Mi? (Sadece 4 Proje Gösterebilisiniz)')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='Kategori Seçin')),
                ('tag', models.ManyToManyField(to='pages.tag', verbose_name='Etiket Seçin')),
            ],
        ),
    ]
