# Generated by Django 4.1.3 on 2023-02-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='tel',
            field=models.IntegerField(default=2, verbose_name='Telefon'),
            preserve_default=False,
        ),
    ]
